---
- name: Install AWS CLI
  yum:
    name: unzip
    state: present

- name: Download AWS CLI v2
  get_url:
    url: https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip
    dest: /tmp/awscliv2.zip

- name: Unzip AWS CLI v2
  unarchive:
    src: /tmp/awscliv2.zip
    dest: /tmp
    remote_src: true

- name: Install AWS CLI v2
  command: /tmp/aws/install -i /usr/local/aws-cli -b /usr/local/sbin

- name: Remove temporary files
  file:
    path: /tmp/aws*
    state: absent
