# Copyright 2023 The Kubernetes Authors.

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

# http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
- name: Unload nouveau
  modprobe:
    name: nouveau
    state: absent
  ignore_errors: true

- name: Add NVIDIA package signing key
  ansible.builtin.apt_key:
    url: https://nvidia.github.io/libnvidia-container/gpgkey
  when: ansible_os_family == "Debian"

- name: Perform a cache update
  apt:
    force_apt_get: true
    update_cache: true
  register: apt_lock_status
  until: apt_lock_status is not failed
  retries: 5
  delay: 10
  when: ansible_os_family == "Debian"

- name: Install packages for building NVIDIA driver kernel module and interacting with s3 endpoint
  become: true
  ansible.builtin.apt:
    pkg:
      - build-essential
      - wget
      - dkms
      - python3-boto3
      - python3-botocore
  when: ansible_os_family == "Debian"

- name: Make /etc/nvidia/ClientConfigToken directory
  become: true
  file:
    path: /etc/nvidia/ClientConfigToken
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Download NVIDIA License Token
  amazon.aws.s3_object:
    endpoint_url: "{{ nvidia_s3_url }}"
    access_key: "{{ nvidia_bucket_access }}"
    secret_key: "{{ nvidia_bucket_secret }}"
    bucket: "{{ nvidia_bucket }}"
    object: "{{ nvidia_tok_location }}"
    dest: /etc/nvidia/ClientConfigToken/client_configuration_token.tok
    mode: get
    ceph: "{{ nvidia_ceph }}"
  retries: 5
  delay: 3

- name: Set Permissions of NVIDIA License Token
  file:
    path: /etc/nvidia/ClientConfigToken/client_configuration_token.tok
    state: file
    owner: root
    group: root
    mode: "0744"

- name: Create GRIDD licensing config
  become: true
  template:
    src: templates/gridd.conf.j2
    dest: /etc/nvidia/gridd.conf
    mode: "0644"

- name: Download NVIDIA driver installer file
  amazon.aws.s3_object:
    endpoint_url: "{{ nvidia_s3_url }}"
    access_key: "{{ nvidia_bucket_access }}"
    secret_key: "{{ nvidia_bucket_secret }}"
    bucket: "{{ nvidia_bucket }}"
    object: "{{ nvidia_installer_location }}"
    dest: /tmp/NVIDIA-Linux-gridd.run
    mode: get
    ceph: "{{ nvidia_ceph }}"
  retries: 5
  delay: 3

- name: Set Permissions of NVIDIA driver installer file
  file:
    path: /tmp/NVIDIA-Linux-gridd.run
    state: file
    owner: root
    group: root
    mode: "0755"

- name: Install NVIDIA driver
  become: true
  ansible.builtin.command:
    cmd: /tmp/NVIDIA-Linux-gridd.run -s --dkms --no-cc-version-check

- name: Remove the NVIDIA driver installer file
  file:
    path: /tmp/NVIDIA-Linux-gridd.run
    state: absent

- name: Cleanup packages for interacting with s3 endpoint
  become: true
  ansible.builtin.apt:
    state: absent
    purge: true
    pkg:
      - python3-boto3
      - python3-botocore
  when: ansible_os_family == "Debian"
